sudo: false
language: go
go:
  - 1.6

cache:
  directories:
    - vendor

before_install:
  - mkdir -p $GOPATH/bin
  - curl -s https://glide.sh/get | sh
install:
  - glide install
script:
  - go test -v $(glide novendor)
  - go build -o terraform-provider-dynadot

deploy:
  provider: releases
  api_key:
    secure: 6stJtSFIliTgKukfPALKyCdf2kLe6YO2H78L/x0qeBbcuncNKQf6WFCVXpqaT0tF4JlFlxNqapbgAHl54uNAbkSUVc24ovzKg5puE7UmYfRrwkG8OeYioAF2tc4LZT5LA8s794m3egOmtBnwNEnp38p/WdHdPo6lw/6sNYCl5IQ2aaMYI95eqmJ6fwuzWqRTFjUe09XE+drqbkeaBYy3icL1hS035LLH3Yp6+1PcQEhZV1FNjzMm8H/94iya25SI3X3xTCjy9GU746Bdz9m+eJRU9DhU9/bnyYCtf93PrqRCrl5cytBRFCOW+TO8LHtnWnqANAkQq3GQW4KcmHBJQ1VmbmUfVv5xV1y/GGUBwVtWYZTaRLBJ0AFB050wVq3eLBjns3BeSMQb9j7fEw6XHKpAmvzzdpmnn7XPN7xDxMYJN62d6sG6GRksOnBNnQ8HN9cFMh140GBFQOpbussb0kjJMGFBTiMXe9+qlaQQdRYag5Z4nTZT8IbXSiRzXYnVdCp9moCi13xXrTpgumUQ5OPwRvM+xvIP/kcnwRgkjeIhbaD8cSXrQ6+QhLAF3eMkze/5jOLAAr8NkEwo7wPQxmgIdS+OUani9aOphAVUCyRa8Dkr455mQ4VPLAVHY4n/gWgmphtMMvfw8/vqjrY1sBqIA6NjvSIARtS9c9A8beM=
  file: terraform-provider-dynadot
  on:
    tags: true
  skip_cleanup: true
